In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], dtype=float)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
# Shape
print(f"The shape of the array is: {arr.shape}")

(3, 3)


In [6]:
# Ndim
print(f"The dimensions of the array is: {arr.ndim}")

The dimensions of the array is: 2


In [7]:
# Size i.e. total number of elements in the array
print(f"The size of the array: {arr.size}")

The size of the array: 9


In [8]:
# Itemsize i.e. size of each value in the array in bytes
print(f"Each element of of the array occupies memory of: {arr.itemsize} bytes and of type: {arr.dtype}")

Each element of of the array occupies memory of: 8 bytes and of type: float64


In [11]:
# Transpose
print(f"The transpose of the array:\n {arr.T}")

The transpose of the array:
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
