In [4]:
import numpy as np

In [5]:
empty_array = np.empty((3, 2), dtype=int)
print(empty_array)

[[-741657184        664]
 [         0          0]
 [         1 1734702190]]


In [6]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [7]:
ones_array = np.ones((1, 1))
print(ones_array)

[[1.]]


In [8]:
full_array = np.full((3,3), fill_value=23)
print(full_array)

[[23 23 23]
 [23 23 23]
 [23 23 23]]


In [9]:
list_data = [10, 20, 30, 40]
arr = np.asarray(list_data)
print(arr)  

[10 20 30 40]


In [10]:
iter_obj = iter(list_data)
arr = np.fromiter(iter_obj, dtype=float)
print(arr)

[10. 20. 30. 40.]


In [16]:
buffer_list = b'Hello World'
print(buffer_list)
arr = np.frombuffer(buffer_list, dtype='S1')
print(arr)

b'Hello World'
[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [19]:
buffer_list = b'Hello World!'
print(buffer_list)
arr = np.frombuffer(buffer_list, dtype='S2') # the buffer_list must be of characters in multiples of 2
print(arr)

b'Hello World!'
[b'He' b'll' b'o ' b'Wo' b'rl' b'd!']


In [21]:
arr = np.arange(start=0, stop=10, step=2, dtype=int)
print(arr)

[0 2 4 6 8]


In [22]:
# Create an array with 5 values evenly spaced between 0 and 100
arr = np.linspace(start=0, stop = 100, num = 5, dtype=int)
print(arr)

[  0  25  50  75 100]


In [24]:
arr = np.logspace(start=0, stop=10, num=5, base=2)
print(arr)

[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]
