In [1]:
import numpy as np

In [4]:
arr = np.array((10, 20, 30, 40, 50))
print(arr)

[10 20 30 40 50]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr = [10, 20, 30, 40]
arr = np.array(arr, dtype=float)
print(arr)

[10. 20. 30. 40.]


In [9]:
arr = [[10, 20], [30, 40]]
arr = np.array(arr, dtype=complex)
print(arr)

[[10.+0.j 20.+0.j]
 [30.+0.j 40.+0.j]]


In [10]:
names = np.array(['John', 'Jane', 'Will'])
joining_dates = np.array(['2017-05-04', '2021-04-09', '2020-06-30'], dtype='M')
age = np.array([45, 90, 100])

In [13]:
print(f"Data types of names: {names.dtype}")
print(f"Data types of joining_dates: {joining_dates.dtype}")
print(f"Data types of age: {age.dtype}")

Data types of names: <U4
Data types of joining_dates: datetime64[D]
Data types of age: int32


In [15]:
arr = ([10, 20, 30])
print(arr.dtype) # This throws an error -> 'list' object has no attribute 'dtype' as expected

AttributeError: 'list' object has no attribute 'dtype'

Data type Conversion

In [18]:
arr = np.array([10, 20, 30])
# Method 1
float_arr = np.array(arr, dtype=float)
print(float_arr)

[10. 20. 30.]


In [25]:
# Method 2
uint_arr = np.uint(arr)
print(f"{uint_arr} of type {uint_arr.dtype}")

[10 20 30] of type uint32


In [26]:
# Method 3
cmplx = arr.astype(complex)
print(cmplx)

[10.+0.j 20.+0.j 30.+0.j]
