In [2]:

import numpy as np


In [3]:
arr = np.array([[1, 2, 3], [11, 22, 33], [4, 5, 6], [8, 9, 10], [20, 30, 40]])
print(arr)

[[ 1  2  3]
 [11 22 33]
 [ 4  5  6]
 [ 8  9 10]
 [20 30 40]]


In [4]:
sum = arr.sum(axis=None)
print(f"Total Sum of the matrix from left to right: {sum}")

Total Sum of the matrix from left to right: 204


In [5]:
sum = arr.sum(axis=0)
print(f"Sum of the matrix column-wise: {sum}")

Sum of the matrix column-wise: [44 68 92]


In [6]:
sum = arr.sum(axis=1)
print(f"Sum of the matrix row-wise: {sum}")

Sum of the matrix row-wise: [ 6 66 15 27 90]


In [7]:
arr = np.random.randn(2, 3)
print(arr)

[[-0.17315268  0.97039336 -0.74131849]
 [-0.45442301 -1.00232067  1.41846285]]


In [10]:
# Matrix (2D) mupltipled with scalar or vector (1D)
arr = np.array([[2, 3],[4, 5]])
arr = np.dot(arr, 3)
print(arr)

[[ 6  9]
 [12 15]]


In [11]:
# This is the matrix multiplication as shape is (2D)
A = np.array([[6, 7],
      [8, 9]])
      
B = np.array([[1, 3],
      [5, 7]])

print(np.dot(A,B))

[[41 67]
 [53 87]]


In [19]:
# Both are 1D. Conflict between matrix and vectors. Dot product is always between vectors.  
# Hence they will be treated as vectors and not matrices.
A = np.array([[1], [2], [3]])
print(A)
B = np.array(([4], [5], [6]))
print(B)
print(f"Result: {np.dot(A.T, B)}")

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
Result: [[32]]
