In [4]:

import numpy as np


In [5]:
arr = np.array([[1, 2, 3], [11, 22, 33], [4, 5, 6], [8, 9, 10], [20, 30, 40]])
print(arr)

[[ 1  2  3]
 [11 22 33]
 [ 4  5  6]
 [ 8  9 10]
 [20 30 40]]


In [6]:
sum = arr.sum(axis=None)
print(f"Total Sum of the matrix from left to right: {sum}")

Total Sum of the matrix from left to right: 204


In [7]:
sum = arr.sum(axis=0)
print(f"Sum of the matrix column-wise: {sum}")

Sum of the matrix column-wise: [44 68 92]


In [8]:
sum = arr.sum(axis=1)
print(f"Sum of the matrix row-wise: {sum}")

Sum of the matrix row-wise: [ 6 66 15 27 90]


In [9]:
arr = np.random.randn(2, 3)
print(arr)

[[-1.5621347   0.40656091  0.35895804]
 [ 1.0304455   0.00328179  0.58941172]]


In [10]:
# Matrix (2D) mupltipled with scalar or vector (1D)
arr = np.array([[2, 3],[4, 5]])
arr = np.dot(arr, 3)
print(arr)

[[ 6  9]
 [12 15]]


In [11]:
# This is the matrix multiplication as shape is (2D)
A = np.array([[6, 7],
      [8, 9]])
      
B = np.array([[1, 3],
      [5, 7]])

print(np.dot(A,B))

[[41 67]
 [53 87]]


In [12]:
# Both are 1D. Conflict between matrix and vectors. Dot product is always between vectors.  
# Hence they will be treated as vectors and not matrices.
A = np.array([[1], [2], [3]])
print(A)
B = np.array(([4], [5], [6]))
print(B)
print(f"Result: {np.dot(A.T, B)}")

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]
Result: [[32]]


In [16]:
arr = np.random.rand(8,1)
print(arr)

[[0.68553514]
 [0.00267111]
 [0.92772432]
 [0.69027024]
 [0.40308963]
 [0.36462042]
 [0.72059612]
 [0.70934084]]


In [29]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a * b
print(c)

[[-0.20064891 -0.11457659  0.2616446 ]
 [-0.49245435  0.45461435  0.34506284]
 [-0.0073302   0.02158278  0.02069777]]


In [30]:
np.subtract?

Call signature:  np.subtract(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'subtract'>
File:            c:\tfs\study\learning-python\.venv\lib\site-packages\numpy\__init__.py
Docstring:      
subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Subtract arguments, element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be subtracted from each other.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input